config/routes.rb
Jbhannah::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  resources :posts, path: '/blog', only: [:index, :show] do
    get 'archive/:year(/:month(/:day))(/page/:page)', action: :index, on: :collection, as: 'archive', constraints: {
      year:  /\d{4}/,
      month: /\d{2}/,
      day:   /\d{2}/,
      page:  /\d+/
    }
    get 'tagged/:tag(/page/:page)', action: :index, on: :collection, as: 'tagged'
  end

  match '/go/:key' => 'welcome#redirect', as: :redirect

  root to: 'welcome#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  class << self
    def months
      published.group_by { |post| post.published_at.beginning_of_month }.keys
    end
  end

  belongs_to :user
  has_and_belongs_to_many :tags
  paginates_per 10

  scope :by_year, lambda { |year|
    t = Time.new(year)
    where("published_at >= ? AND published_at < ?", t, t + 1.year)
  }
  scope :by_month, lambda { |year, month|
    t = Time.new(year, month)
    where("published_at >= ? AND published_at < ?", t, t + 1.month)
  }
  scope :by_day, lambda { |year, month, day|
    t = Time.new(year, month, day)
    where("published_at >= ? AND published_at < ?", t, t + 1.day)
  }

  scope :tagged, lambda { |tag|
    tag = Tag.find_by_slug!(tag) unless tag.is_a?(Tag)
    joins(:tags).where(tags: { id: tag.id })
  }

  scope :published, where(published: true)
  default_scope order('published_at DESC')

  before_validation :update_published_at, :set_slug
  validates_presence_of :title, :slug, :user_id, :body

  auto_html_for :body do
    redcarpet
    image
    flickr(link_options: { rel: :external })
    twitter(align: :center)
    youtube
    vimeo
    gist
  end

  def to_param
    slug
  end

  def prev
    Post.where("published_at < ?", published_at).first if published?
  end

  def next
    Post.where("published_at > ?", published_at).last if published?
  end

  private
  def set_slug
    self.slug = title.parameterize
  end

  def update_published_at
    self.published_at = Time.now if published? and published_at.nil?
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :posts

  before_validation :set_slug
  validates_presence_of :name, :slug

  default_scope order('slug ASC')

  def to_s
    name
  end

  def to_param
    slug
  end

  private
  def set_slug
    self.slug = name.parameterize
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :remember_me

  has_many :posts

  def to_s
    Settings.name if self == User.first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  cache_sweeper :post_sweeper

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_path
  end
end

app/controllers/post_sweeper.rb
class PostSweeper < ActionController::Caching::Sweeper
  observe Post

  def after_create(post)
    expire_cache_for(post)
  end

  def after_update(post)
    expire_cache_for(post)
  end

  def after_destroy(post)
    expire_cache_for(post)
  end

  private
  def expire_cache_for(post)
    # Currently, there's no way to run expire_action from a sweeper
    # triggered by rails_admin. Ideally, this would run:

    # expire_fragment "latest_posts"
    # expire_fragment "post_months"
    # expire_action controller: "/posts", action: :index
    # expire_action controller: "/posts", action: :show, id: post.slug

    # Instead, it's easier to just clear the entire cache for now.
    Rails.cache.clear
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource find_by: :slug
  caches_action :index, :show, layout: false, cache_path: lambda { |c| c.params }, if: lambda { request.format.html? }
  caches_action :index, if: lambda { request.format.atom? }

  def index
    if params[:year]
      @date = Time.new(params[:year], params[:month], params[:day])

      if params[:month]
        if params[:day]
          @posts = @posts.by_day(params[:year], params[:month], params[:day])
        else
          @posts = @posts.by_month(params[:year], params[:month])
        end
      else
        @posts = @posts.by_year(params[:year])
      end
    elsif params[:tag]
      @tag   = Tag.find_by_slug!(params[:tag])
      @posts = @posts.tagged(@tag)
    end

    @posts = @posts.page(params[:page])

    respond_to do |format|
      format.html
      format.atom unless params[:page] or params[:year]
    end
  end

  def show
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def redirect
    key = params[:key]

    if Settings.social[key]
      redirect_to Settings.social[key]["url"], status: :moved_permanently
    else
      raise ActionController::RoutingError.new("Invalid key")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def age
    d  = Date.today
    bd = Date.new(Settings.birthday.year, Settings.birthday.month, Settings.birthday.day)

    a = d.year - bd.year
    a = a - 1 if (
       bd.month >  d.month or
      (bd.month >= d.month and bd.day > d.day)
    )
    a
  end

  def latest_tweets
    begin
      Twitter.user_timeline(Settings.handle).first(5)
    rescue
      []
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def latest_posts
    Post.published.first(5)
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_tweets.html.erb
<% cache "latest_tweets", expires_in: 60 do %>
<div class="sidebar_block" id="latest_tweets">
  <h3><%= link_to "Tweets", Settings.social.twitter.url, rel: :external %></h3>

  <%= "Twitter could not be reached, or another error occurred." if latest_tweets.empty? %>
  <ul>
  <% latest_tweets.each do |tweet| %>
    <li class="tweet">
      <%= auto_html(tweet.text) { link(rel: :external) } %>
      <%= link_to Settings.social.twitter.url + "/status/#{tweet.id}", rel: :external do %>
        <time datetime="<%= tweet.created_at.utc.iso8601 %>"><%= time_ago_in_words(tweet.created_at) + " ago" %></time>
      <% end %>
    </li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<% cache(action_suffix: params.to_s + "_header") do %>
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title><%= yield(:title).split.join(' ') + " – " if content_for?(:title) %><%= Settings.name %></title>

  <%= favicon_link_tag asset_path("favicon.ico") %>
  <%= auto_discovery_link_tag :atom, { controller: :posts, action: :index, format: :atom } %>

  <%= stylesheet_link_tag :application, params[:controller], media: :all %>

  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" %>
  <%= javascript_include_tag params[:controller], :application %>

  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %> <%= action_name %>">
<div id="root">
<div id="root_header"></div>

<div id="main">
  <header id="header">
    <hgroup id="site_title">
      <h1><%= link_to_unless_current Settings.name, root_path %></h1>
      <h2><%= Settings.handle %></h2>
    </hgroup>
  </header>
  <div id="content">
<% end %>

    <%= yield %>

<% cache "sidebar_top" do %>
  </div>
</div>
<div id="sidebar">
  <%= link_to image_tag("avatar.png", id: "avatar", alt: Settings.name, title: Settings.name), root_path %>

  <nav id="social_menu">
    <ul>
    <% Settings.social.each do |k, v| %>
      <li id="<%= k %>"><%= link_to image_tag("social/#{k}.png", class: "social_icon", alt: v["name"], title: v["name"]), redirect_path(k), rel: :external %></li>
    <% end %>
    </ul>
  </nav>
<% end %>

  <%= yield :sidebar %>

<% cache "footer" do %>
</div>

<div id="root_footer"></div>
</div>

<footer id="footer">
  Copyright © 2012<%= '-' + Date.today.year.to_s if Date.today.year > 2012 %> <%= link_to Settings.name, root_url %>.
  <%= link_to "Some Rights Reserved", "http://creativecommons.org/licenses/by-nc-sa/3.0/", rel: [:external, :license] %>.
  <%= link_to "Website code on GitHub", "https://github.com/jbhannah/jbhannah", rel: :external %>.
</footer>
</body>
</html>
<% end %>

app/views/layouts/posts.html.erb
<% content_for :title do %>
  <%= @post.title + " –" if @post %>
  Blog
  <% if @date %>
    –
    <%= @date.strftime('%e') if params[:day] %>
    <%= @date.strftime('%B') if params[:month] %>
    <%= @date.strftime('%Y') %>
  <% elsif @tag %>
    – <%= @tag %>
  <% end %>
  <%= "– Page " + params[:page] if params[:page] %>
<% end %>

<% content_for :sidebar do %>
  <%= render partial: 'posts/months' %>

  <%= render partial: 'posts/latest' %>

  <%= render partial: 'layouts/tweets' %>
<% end %>

<%= render template: 'layouts/application' %>

app/views/posts/_latest.html.erb
<% cache "latest_posts" do %>
<div class="sidebar_block" id="latest_posts">
  <h3><%= link_to "Blog", posts_path %></h3>

  <ul>
  <%= content_tag_for(:li, latest_posts, :latest) do |post| %>
    <%= link_to post.title, post %>
    <div class="meta">
      <time datetime="<%= post.published_at.utc.iso8601 %>"><%= post.published_at.strftime("%e %B %Y") %></time>
    </div>
  <% end %>
  </ul>
</div>
<% end %>

app/views/posts/_months.html.erb
<% cache "post_months" do %>
<div class="sidebar_block" id="post_months">
  <h3>Archives</h3>

  <ul>
  <% Post.months.each do |month| %>
    <li>
      <%= link_to month.strftime("%B %Y"), archive_posts_path(year: month.year, month: month.strftime("%m")) %>
      (<%= Post.by_month(month.year, month.month).count %>)
    </li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/posts/_nav.html.erb
<nav class="posts_nav">
  <div class="post_nav prev_post"><%= link_to "« " + @post.prev.title, @post.prev if @post.prev %>&nbsp;</div>
  <div class="post_nav next_post">&nbsp;<%= link_to @post.next.title + " »", @post.next if @post.next %></div>
</nav>

app/views/posts/_post.html.erb
<%= content_tag_for :article, post do %>
  <header class="post_header">
    <h1><%= link_to_unless_current post.title, post %></h1>

    <div class="meta">
      Posted by <%= post.user.to_s.split.first %>
      <% if post.published_at %>
        <time pubdate datetime="<%= post.published_at.utc.iso8601 %>"><%= post.published_at.strftime("on %A, %e %B %Y at %H:%M %Z") %></time>
      <% else %>
        <time pubdate datetime="<%= post.created_at.utc.iso8601 %>"><%= post.created_at.strftime("on %A, %e %B %Y at %H:%M %Z") %></time>
      <% end %>
      –
      <%= link_to "Permalink", post %>
    </div>

    <% unless post.tags.empty? %>
    <div class="tags">
      Tagged
      <ul class="delimited">
      <% post.tags.each do |pt| %>
        <li><%= link_to pt, tagged_posts_path(pt) %></li>
      <% end %>
      </ul>
    </div>
    <% end %>
  </header>

  <%= post.body_html %>
<% end %>

app/views/posts/index.html.erb
<% if @date %>
  <h2>
    Archive for
    <%= @date.strftime('%e') if params[:day] %>
    <%= @date.strftime('%B') if params[:month] %>
    <%= @date.strftime('%Y') %>
  </h2>
<% elsif @tag %>
  <h2>Posts tagged "<%= @tag %>"</h2>
<% end %>

<%= render @posts or "No posts matched your criteria." %>

<%= paginate @posts %>

app/views/posts/show.html.erb
<%= render @post %>

<%= render 'nav' %>

<div id="disqus_thread"></div>

app/views/welcome/index.html.erb
<% cache do %>
<div id="bio">
<%= Settings.name.split.first %> is a <%= age %>-year-old

<ul class="delimited and comma">
  <li>web developer</li>
  <li>sysadmin-in-training</li>
  <li>Mac addict</li>
  <li><abbr title="Computer Information Systems">CIS</abbr> major at <%= link_to "ASU", "http://www.asu.edu", rel: :external %></li>
  <li>blogger</li>
  <li>writer</li>
  <li><%= link_to "undead rogue", "http://us.battle.net/wow/en/character/earthen-ring/Adarystus/", rel: :external %></li>
  <li><%= link_to "Mormon", "https://mormonorg.lds.org/me/18K9/", rel: :external %></li>
  <li>geek-of-all-trades</li>
</ul>

who lives with his <%= link_to "cat", "http://www.flickr.com/photos/jbhannah/sets/72157626784508774/", rel: :external %> in Tempe, AZ.
</div>
<% end %>

<%= render partial: 'posts/latest' %>

<%= render partial: 'layouts/tweets' %>